name: deployment-orchestrator
project: release-engineering
point_of_contact_1: release-owner@example.com
point_of_contact_2: release-backup@example.com


visibility: private
access_scope: individual
security_severity: medium

