apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reusable.fullname" . }}
  labels:
    {{- include "reusable.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "reusable.fullname" . | quote }}
  template:
    metadata:
      labels:
        {{- include "reusable.labels" . | nindent 8 }}
        {{- toYaml .Values.podLabels | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "reusable.serviceAccountName" . }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: {{ include "reusable.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          env: {{ toYaml .Values.env | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
