apiVersion: v1
kind: Service
metadata:
  name: {{ include "reusable.fullname" . }}
  labels:
    {{- include "reusable.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ include "reusable.fullname" . | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
