{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reusable.serviceAccountName" . }}
  labels:
    {{- include "reusable.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- if eq .Values.cloud.provider "aws" }}{{ toYaml .Values.cloud.aws.serviceAccountAnnotations | nindent 4 }}{{- end }}
    {{- if eq .Values.cloud.provider "azure" }}{{ toYaml .Values.cloud.azure.serviceAccountAnnotations | nindent 4 }}{{- end }}
{{- end }}
