#!/usr/bin/env python3
"""Generate the repository POLICY_INDEX.md from policy and rule files."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ("opa", "semgrep", "trivy", "TFLint", "terrascan")
EXTENSIONS = {".rego", ".yml", ".yaml", ".hcl", ".json"}


def metadata(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"(?im)^\s*#?\s*severity\s*:\s*([a-z]+)", text)
    severity = match.group(1).lower() if match else "medium"
    return severity if severity in {
        "critical",
        "high",
        "medium",
        "low",
        "info",
    } else "medium", "active"


def main() -> None:
    rows = []
    for tool in TOOLS:
        base = ROOT / tool
        if not base.exists():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or path.suffix.lower() not in EXTENSIONS:
                continue
            if (
                "exceptions" in path.parts
                or "exception" in path.parts
                or path.name in {".tflint.hcl"}
            ):
                continue
            if path.suffix.lower() == ".json" and path.with_suffix(".rego").exists():
                continue
            rel = path.relative_to(ROOT).as_posix()
            stem = path.stem.lower()
            match = re.match(r"([a-z]+)_([a-z0-9-]+)_(\d{3})", stem)
            policy_id = "-".join(match.groups()) if match else f"{tool.lower()}-{stem}"
            severity, status = metadata(path)
            relative_parts = path.relative_to(ROOT).parts
            category = relative_parts[1] if len(relative_parts) > 1 else tool.lower()
            rows.append((policy_id, tool.lower(), category, severity, status, rel))

    lines = [
        "# Policy catalogue",
        "",
        "Generated by `scripts/generate_policy_index.py`. Do not edit manually.",
        "",
        "| policy id | tool | category | severity | status | path |",
        "|---|---|---|---|---|---|",
    ]
    lines.extend(f"| {a} | {b} | {c} | {d} | {e} | {f} |" for a, b, c, d, e, f in rows)
    (ROOT / "POLICY_INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(rows)} policy entries")


if __name__ == "__main__":
    main()
